services:
    nginx:
        env_file:
        - .env
        build:
            context: ./image/
            dockerfile: Dockerfile
            args:
            - REGISTRY=${REGISTRY}
            - NGINX_VERSION=${NGINX_VERSION}
        image: nginx-proxy:${NGINX_VERSION}
        container_name: nginx
        restart: always
        volumes:
        # - ./.volumes/etc/nginx:/etc/nginx
        - data:/etc/nginx
        # network_mode: host
        ports:
        - 80:80
        - 443:443
        cap_add:
        - NET_BIND_SERVICE
    #     depends_on:
    #     - init-volumes

    # init-volumes:
    #     image: alpine:latest
    #     command: ["sh", "-c", "chown -R 101:101 /volumes"]
    #     volumes:
    #     - ./.volumes:/volumes
    #     - ./.volumes/etc/nginx:/etc/nginx
    #     - ./.volumes/certs:/etc/certs

volumes:
  data:
    driver: local
