services:
  nginx:
    env_file:
    - .env
    build:
      context: ./image/
      dockerfile: Dockerfile
      args:
      - REGISTRY=${REGISTRY}
      - NGINX_VERSION=${NGINX_VERSION}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - NO_PROXY=${NO_PROXY}
    image: nginx-proxy:${NGINX_VERSION}
    container_name: nginx
    restart: always
    volumes:
    - data:/etc/nginx
    # for dev
    # - ./image/sites.yaml:/etc/nginx/sites.yaml
    # - ./image/config_gen.py:/usr/local/bin/config_gen.py
    ports:
    - 80:80
    - 443:443
    cap_add:
    - NET_BIND_SERVICE
    networks:
    - nginx
    - reverse_proxy

volumes:
  data:
    driver: local

networks:
  nginx:
    driver: bridge
    attachable: true
    driver_opts:
      com.docker.network.driver.mtu: 1400
  # used accross services to interconnect with nginx
  reverse_proxy:
    external: true
  # docker network create reverse_proxy
